### PR TITLE
Singularity container for the MPAS-BR

### PR DESCRIPTION
**Pull request by cfbastarz**
This PR adds a singularity container to run the MPAS-BR software. The container is provided as a bootstrap file (`mpas-tools-br.def`), which can be used to customize and build the container. A pre-built image can be pulled from the Sylabs Cloud, so users don't have to worry about the build process. An advantage of the container is that it already comes with the MPAS-Tools pre-installed, along with GNU C and Fortan compilers, MPI, Python, jigsaw and metis software. A `Vagrantfile` is also provided for use with Mac OS X (tested) and potentially with Windows (with WSL - not tested) for users on other platforms. Among these files, reference namelists are also provided to set up MPAS for the baroclinic instability simulation (following Pedro Peixoto's classes). Instructions on how to build and run the MPAS-BR software inside the Singularity container are provided within the `README.md` file.

The files were put inside the `local_software/mpas-tools-br` directory.

```
local_software/
├── mpas-tools-br
    ├── mpas-tools-br.def
    ├── namelists
    │   ├── ref-namelist.atmosphere
    │   ├── ref-stream_list.atmosphere.output
    │   └── ref-streams.atmosphere
    ├── README.md
    └── Vagrantfile
```

Feel free to modify it as needed to best fit the project.

Cheers,

Carlos Frederico Bastarz

### CODE REVIEW

**Comment by favba** [comment]
That is really nice! I never used singularity before.
I'll try following the steps described in the README file to see if everything works as expected.

**Comment by pedrospeixoto** [comment]
Great, feel free to merge.

Prof. Dr. Pedro da Silva Peixoto
Associate Professor
Applied Mathematics
University of São Paulo (USP <http://www.usp.br/>)

www.ime.usp.br/~pedrosp


Em qui., 23 de nov. de 2023 às 12:33, Felipe A. V. de Bragança Alves <
***@***.***> escreveu:

**Comment by favba** [comment]
Hi @cfbastarz , sorry it took me a while to get back to this PR.
I just tested following the steps you provided (at least to get the MPAS compiled inside the singularity container) and it works well!

May I ask two modifications in the README though?

1. Could you point out in the beginnig of the file that another available name/software for `singularity` is `apptainer` ?

Although you provide the steps to install singularity using conda my personal preference is installing software using the distro mechanism (debian in my case) whenever its possible and not too cumbersome.
It was easier for me to find the `apptainer` deb package than `singularity`. It seems there are 3 versions of singularity out there (I read about the history of it here: https://en.wikipedia.org/wiki/Singularity_%28software%29#History)
I downloaded `apptainer` for debian here: https://github.com/apptainer/apptainer/releases

2. Could you move the `Building the SIF image` section  to the end of the README? 

I ask that because some dumb user might notice that you are providing pre-built images only after building their own image. Of couse that dumb user was me :laughing: . Somehow I missed thed very first sentence of that section...

**Comment by cfbastarz** [comment]
Hi @favba, thanks for taking the time checking the instructions in the README.md file. Indeed, Singularity is now Apptainer; I read about it somewhere before, but did not tried it at the time. I made the changes you requested and also checked the compatibility between `singularity` and `apptainer` commands. If more changes are needed, please let me know.

Cheers,

Carlos Frederico Bastarz

**Review by favba — APPROVED** [review]

**Comment by favba** [comment]
Thank you @cfbastarz , this is a great addition to the code!

**Pull request merged**
